# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements. See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership. The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the License for the
# specific language governing permissions and limitations
# under the License.
#


apiVersion: v1
kind: Service
metadata:
  labels:
    app: fineract-app
  name: fineract-app
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9080
  selector:
    app: fineract-app
    tier: backend
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fineract-app
  labels:
    app: fineract-app
spec:
  selector:
    matchLabels:
      app: fineract-app
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fineract-app
        tier: backend
    spec:
      # initContainers:
      #   - name: init-mydb
      #     image: busybox:1.28
      #     command: ['sh', '-c', 'echo -e "Checking for the availability of MYSQL server deployment"; while ! nc -z "fineractmysql" 3306; do sleep 1; printf "-"; done; echo -e " >> MYSQL server has started";']
      containers:
      - name: fineract-app
        image: ankitzen/fineract-app:latest
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "0.5Gi"
        # livenessProbe:
        #   httpGet:
        #     path: /fineract-provider/actuator/health/liveness
        #     port: 8080
        #   initialDelaySeconds: 180
        #   periodSeconds: 1
        # readinessProbe:
        #   httpGet:
        #     path: /fineract-provider/actuator/health/readiness
        #     port: 8080
        #   initialDelaySeconds: 180
        #   periodSeconds: 1
        env:
        - name: FINERACT_NODE_ID
          value: '1'
        - name: FINERACT_HIKARI_DRIVER_CLASS_NAME
          value: org.mariadb.jdbc.Driver
        - name: FINERACT_HIKARI_JDBC_URL
          value: jdbc:mariadb://mariadb-aks:3306/fineract_tenants
        - name: FINERACT_HIKARI_USERNAME
          value: root
          # valueFrom:
          #   secretKeyRef:
          #     name: fineract-tenants-db-secret
          #     key: username
        - name: FINERACT_HIKARI_PASSWORD
          value: fzccrSebKI
          # valueFrom:
          #   secretKeyRef:
          #     name: fineract-tenants-db-secret
          #     key: password
        - name: FINERACT_DEFAULT_TENANTDB_HOSTNAME
          value: mariadb-aks
        - name: FINERACT_DEFAULT_TENANTDB_PORT
          value: '3306'
        - name: FINERACT_DEFAULT_TENANTDB_UID
          value: root
        - name: FINERACT_DEFAULT_TENANTDB_PWD
          value: fzccrSebKI
          # valueFrom:
          #   secretKeyRef:
          #     name: fineract-tenants-db-secret
          #     key: password
        - name: FINERACT_DEFAULT_TENANTDB_CONN_PARAMS
          value: ''
        - name: JAVA_TOOL_OPTIONS
          value: '-Xmx1G'
        - name: FINERACT_SERVER_SSL_ENABLED
          value: 'false'
        - name: FINERACT_SERVER_PORT
          value: '9080'
        ports:
        - containerPort: 80
          name: fineract-app
